// <auto-generated />
using Benday.InvoiceApp.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Benday.InvoiceApp.Api.Migrations
{
    [DbContext(typeof(InvoiceDbContext))]
    partial class InvoiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Benday.InvoiceApp.Api.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Benday.InvoiceApp.Api.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("InvoiceDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("Date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("OwnerClientIDFK");

                    b.HasKey("Id");

                    b.HasIndex("OwnerClientIDFK");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Benday.InvoiceApp.Api.InvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("InvoiceID");

                    b.Property<string>("ItemDescription");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("Quantity");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceID");

                    b.ToTable("InvoiceLine");
                });

            modelBuilder.Entity("Benday.InvoiceApp.Api.Invoice", b =>
                {
                    b.HasOne("Benday.InvoiceApp.Api.Client", "Client")
                        .WithMany()
                        .HasForeignKey("OwnerClientIDFK")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Benday.InvoiceApp.Api.InvoiceLine", b =>
                {
                    b.HasOne("Benday.InvoiceApp.Api.Invoice", "ParentInvoice")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
